### ISSUE TITLE
你好，请问如何开启128M？

### ISSUE THREAD

**Issue by finalloading** [nivrrex/WNDR4300#1]
我在网上搜索：说是在Makefile里面配置，但是现在的makefile 变化了好像，完全不知道怎么办，求告知，谢谢

**Comment by nivrrex** [comment]
我是用imagebuilder编译的
1. 下载最新的19.07.X的openwrt-imagebuilder-19.07.x-ar71xx-nand.Linux-x86_64.tar.xz包
2. 解压缩后，修改目录下的target/linux/ar71xx/image/legacy.mk 文件
3. 将其中的 23552k(ubi),25600k@0x6c0000(firmware) 修改为 120832k(ubi),122880k@0x6c0000(firmware)
4. 然后make image PROFILE="WNDR4300V1" PACKAGES="luci luci-i18n-base-zh-cn luci-i18n-firewall-zh-cn"编译即可

**Comment by nivrrex** [comment]
我看了最新的 openwrt-sdk-19.07.x-ar71xx-nand_gcc-7.5.0_musl.Linux-x86_64.tar.xz 源码包，也有这个文件
应该可以做对应的修改后，按需求编译即可

**Comment by finalloading** [comment]
非常感谢，我之前一直以为是makefile文件，原来是legacy.mk.
